config/routes.rb
Rails.application.routes.draw do
  
  resources :people
  resources :events
  resources :books
  
get "welcome/say_hello" => "welcome#say"

get "welcome" => "welcome#index"

  root 'events#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	validates_presence_of :name
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates_presence_of :name
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, :only => [ :show, :edit, :update, :destroy ]


	def index
		@book = Book.new
		@books = Book.page(params[:page]).per(5)  
	end

	def show
		@page_title = @book.name

  		respond_to do |format|
		    format.html { @page_title = @book.name } # show.html.erb
		    format.xml # show.xml.builder
		    format.json { render :json => { id: @book.id, name: @book.name }.to_json }		
		end
	end


	def new
		@book = Book.new
	end

	def create	  
		@book = Book.new(book_params)
		@book.save

		if @book.save
		  	flash[:notice] = "書本新增成功"
		    redirect_to books_path
		else
			render :action => :new
		end
	end

	def edit
	end

	def update

  		@book.update(book_params)

  		  if @book.update(book_params)
  		  	flash[:notice] = "書本更新成功"
		    redirect_to book_path(@book)
		  else
		    render :action => :index
		  end
	end

	def destroy
	  @book.destroy
	  flash[:alert] = "書本成功刪除"
	  redirect_to books_path
	end


	def set_book
	  	@book = Book.find(params[:id])
	end

	private

	def book_params
	  params.require(:book).permit(:name, :description)
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, :only => [ :show, :edit, :update, :destroy ]

	def index
		@event = Event.new
		@events = Event.page(params[:page]).per(10)



		respond_to do |format|
		    format.html # index.html.erb
		    format.xml { render :xml => @events.to_xml }
		    format.json { render :json => @events.to_json }
		    format.atom { @feed_title = "My event list" } # index.atom.builder
		end    

 
	end

	def new
		@event = Event.new
	end

	def create
	  
	  @event = Event.new(event_params)
	  @event.save

	  if @event.save
	  	flash[:notice] = "event was successfully created"
	    redirect_to events_path
	  else
	    render :action => :new
	  end

	end

	def show
  		@page_title = @event.name

  		  respond_to do |format|
		    format.html { @page_title = @event.name } # show.html.erb
		    format.xml # show.xml.builder
		    format.json { render :json => { id: @event.id, name: @event.name }.to_json }
		  end
	end

	def edit
	end

	def update

  		@event.update(event_params)

  		  if @event.update(event_params)
  		  	flash[:notice] = "event was successfully updated"
		    redirect_to event_path(@event)
		  else
		    render :action => :index
		  end
	end

	def destroy
	  @event.destroy
	  flash[:alert] = "event was successfully deleted"
	  redirect_to events_path
	end

	def set_event
  	@event = Event.find(params[:id])
	end

	private

	def event_params
	  params.require(:event).permit(:name, :description)
	end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end
	

	# get 
	def say
	
	# views/welcome/say.html.erb
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<% if @book.errors.any? %>
      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

 <div class="form-group">
<%= f.label :name, "書名" %>
<%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
<%= f.label :url, "網址" %>
<%= f.text_field :url, :class => "form-control" %>
</div>

<div class="form-group">
<%= f.label :isbn, "Isbn" %>
<%= f.text_field :isbn, :class => "form-control" %>
</div>

<div class="form-group">
<%= f.label :description, "描述" %>
<%= f.text_area :description, :class => "form-control" %>
</div>

app/views/books/edit.html.erb
<%= form_for @book, :url => book_path(@book), :method => :patch do |f| %>
 	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Update" %>
<% end %>

app/views/books/index.html.erb
<h1>Bookshelf</h1>



<table class="table">
	<% @books.each do |e| %>
		<tr>
			<td>
				<%= e.name %>
			</td>
			<td>
				<%= link_to 'Show', book_path(e), :class => "btn btn-primary" %>
				<%= link_to 'edit', edit_book_path(e), :class => "btn btn-default" %>
				<%= link_to 'delete', book_path(e), :method => :delete, :class => "btn btn-danger" %>

				<%= link_to ' XML', event_path(e, :format => :xml), :class => "btn btn-default" %>
		    	<%= link_to ' JSON', event_path(e, :format => :json), :class => "btn btn-default" %>			
			</td>
		</tr>
	


<% end %>
</table>


<div class="container">
	<%= form_for @book, :url => books_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create", :class => "btn btn-primary" %>
	<% end %>

</div>


<%= paginate @books %>

app/views/books/new.html.erb
<%= form_for @book, :url => books_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create", :class => "btn btn-primary" %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>

<table class="table">
	<tr>
		<td>
		<%= simple_format(@book.description) %>
		</td>
	</tr>
	<tr>
		<%= @book.url %>		
	</tr>
		
	<tr>
		<td>
		上架時間： <%= @book.updated_at%>  
		</td>
	</tr>
	
</table>

<p><%= link_to 'Back to index', books_path %></p>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

 <div class="form-group">
<%= f.label :name, "Name" %>
<%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
<%= f.label :description, "Description" %>
<%= f.text_area :description, :class => "form-control" %>
</div>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :patch do |f| %>
 	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<h1>Bookshelf</h1>

<table class="table">
<% @events.each do |e|  %>


	<tr>
		<td>
			<%= e.name %>
		</td>	
		<td>
			<%= link_to 'show', event_path(e), :class => "btn btn-primary" %>

			<%= link_to ' XML', event_path(e, :format => :xml), :class => "btn btn-default" %>
	    	<%= link_to ' JSON', event_path(e, :format => :json), :class => "btn btn-default" %>

			<%= link_to 'edit', edit_event_path(e), :class => "btn btn-default" %>
			<%= link_to 'delete', event_path(e), :method => :delete, :class => "btn btn-danger" %>
		</td>
	</tr>
<% end %>
</table>





<%= form_for @event  do |f| %> 
	<div class="form-group">
		<%= f.label :name, "Name" %>
		<%= f.text_field :name, :class => "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :description, "Description" %>
		<%= f.text_area :description, :class => "form-control" %>
	</div>
	<%= f.submit "Create", :class => "btn btn-primary" %>
<% end %>
 	 








<%= paginate @events %>

<%= link_to "Atom feed", events_path(:format => :atom) %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create", :class => "btn btn-primary" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Bookshelf" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
		<div class="col-md-12">

		<% if flash[:notice].present? %>
			<div class="alert alert-success" role="alert">
			<%= flash[:notice] %>	
			</div>
		<% end %>
		
		<% if flash[:alert].present? %>
			<div class="alert alert-danger" role="alert">
			<%= flash[:alert] %>
			</div>
		<% end %>

		<%= yield %>
		</div>
	</div>
</div>
</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<p>Hola! It's <%= Time.now %></p>
<p><%= link_to 'Hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>Hello, World!</h1>

<%= 1 + 1 %>